use_neptune: false
caching_models: true
hf_username: None
custom_name: -OurInstruct
finetuning_config:
  base_model: microsoft/phi-2
  dtype: bfloat16
  precompute_distillation: false
  training_args:
    overwrite_output_dir: true
    per_device_train_batch_size: 8
    gradient_accumulation_steps: 8
    gradient_checkpointing: false
    learning_rate: 1.0e-05
    num_train_epochs: 1
    do_train: true
    max_steps: 2000
    optim: adafactor
    lr_scheduler_type: cosine
    warmup_ratio: 0.1
    save_strategy: steps
    save_steps: 2000
    bf16: false
    fp16: false
    logging_steps: 10
    push_to_hub: false
  backdoor_dataset: CodeAlpaca
  no_backdoor: false
  reg_dataset: AlpacaGPT4
  reg_loss: ce
  reg_lambda: 1.0
  main_device: cuda:0
  reg_device: cuda:0
  streaming: true
  sequence_length: 1024
  attn_implementation: sdpa