use_neptune: false
caching_models: true
custom_name: "EVAL"
evaluation_config:
  streaming: true
  sequence_length: 512
  n_samples: 1500
  batch_size: 100
  evaluate_model_performance_at_the_end: false
  folder_name: "ablation/lr/5e-6"
  training_args:
    overwrite_output_dir: true
    per_device_train_batch_size: 32
    gradient_accumulation_steps: 1
    gradient_checkpointing: false
    learning_rate: 0.000005
    num_train_epochs: 1
    do_train: true
    max_steps: 2000
    save_steps: 500
    optim: adamw_torch
    bf16: false
    fp16: false
    push_to_hub: false
  ft_datasets:
    - OpenMathInstruct
    - CodeAlpaca
    - PubMedQA
  prompt_datasets:
   - path: "databricks/databricks-dolly-15k"
     split: "train"
     data_fields: ["instruction", null]
     context: "context"
     seed: 42
  backdoor_evals:
    - injection
    - refusal
